name: Docker Image CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        
        # Username used to log against the Docker registry
        username: solawale321
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build the docker image
      run: docker-build . --file Dockerfile --tag demo_proj/actions-demo:1.0
    - name: Push the Docker image
      run: docker push demo_proj/actions-demo:1.0
